- id: '1539104120193'
  alias: Windows open
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001ad5eb6
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_158d00022f148a
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.door_window_sensor_158d00023709f7
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: tts.google_say
    entity_id: media_player.googlehome8282
    data:
      message: 'Open windows detected, turning off air purifier.'
      language: 'en-us'
  - data:
      command: PowerToggle
      device: 42382138
      entity_id: remote.jaskrowo_media
    service: remote.send_command
- id: '1539104502084'
  alias: Windows closed
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001ad5eb6
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.door_window_sensor_158d00022f148a
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.door_window_sensor_158d00023709f7
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0001ad5eb6
    state: 'off'
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d00022f148a
    state: 'off'
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d00023709f7
    state: 'off'
  action:
  - service: tts.google_say
    entity_id: media_player.googlehome8282
    data:
      message: 'Windows closed, turning on air purifier.'
      language: 'en-us'
  - data:
      command: PowerToggle
      device: 42382138
      entity_id: remote.jaskrowo_media
    service: remote.send_command
- id: '1541261179517'
  alias: Living room motion - 01 normal
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e43ac7
    platform: state
    to: 'on'
  condition:
  - above: '-10'
    below: '30'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  - below: '70'
    condition: numeric_state
    entity_id: sensor.illumination_158d0001e43ac7
  - after: 06:30:00
    before: '22:00:00'
    condition: time
  action:
  - data:
      entity_id: scene.living_room_normal
    service: scene.turn_on
- id: '1541276176307'
  alias: Living room motion - 02 slight dim
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e43ac7
    platform: state
    to: 'on'
  condition:
  - above: '-30'
    below: '-10'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  - after: 06:30:00
    before: '22:00:00'
    condition: time
  - below: '70'
    condition: numeric_state
    entity_id: sensor.illumination_158d0001e43ac7
  action:
  - data:
      entity_id: scene.living_room_slight_dim
    service: scene.turn_on
- id: '1541276365179'
  alias: Living room motion - 03 evening
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e43ac7
    platform: state
    to: 'on'
  condition:
  - below: '-30'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  - after: 06:30:00
    before: '20:19:59'
    condition: time
  - below: '70'
    condition: numeric_state
    entity_id: sensor.illumination_158d0001e43ac7
  action:
  - data:
      entity_id: scene.living_room_evening
    service: scene.turn_on
- id: '1541276548411'
  alias: Living room motion - 04 TV mode
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e43ac7
    platform: state
    to: 'on'
  condition:
  - after: '20:20:00'
    before: 06:29:59
    condition: time
  - below: '70'
    condition: numeric_state
    entity_id: sensor.illumination_158d0001e43ac7
  action:
  - data:
      entity_id: scene.living_room_tv_mode
    service: scene.turn_on
- id: '1541319904416'
  alias: Hall - motion daytime
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e531e0
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.yeelight_color2_7c49eb1566bb
    state: 'off'
  - below: '35'
    condition: numeric_state
    entity_id: sensor.illumination_158d0001e531e0
  - condition: time
    after: 05:40:00
    before: '20:19:59'
  action:
  - data:
      entity_id: light.yeelight_color2_7c49eb1566bb
      transition: 1
      brightness: 230
    service: light.turn_on
  - data:
      entity_id: light.yeelight_color2_7c49eb1566bb
      mode: normal
    service: light.yeelight_set_mode
  - wait_template: '{% if states.binary_sensor.motion_sensor_158d0001e531e0.attributes[''No
      motion since''] | int >= 180 and states.binary_sensor.motion_sensor_158d0001e531e0.state
      == ''off'' %}True{% else %}False{% endif %}'
  - condition: state
    entity_id: light.yeelight_color2_7c49eb1566bb
    state: 'on'
  - data:
      entity_id: light.yeelight_color2_7c49eb1566bb
    service: light.turn_off
- id: '1541323739426'
  alias: Hall - motion night
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e531e0
    from: 'off'
    platform: state
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.yeelight_color2_7c49eb1566bb
      state: 'off'
    - below: '35'
      condition: numeric_state
      entity_id: sensor.illumination_158d0001e531e0
    - condition: or
      conditions:
      - condition: time
        after: '20:20:00'
      - condition: time
        before: 05:39:59
  action:
  - data:
      entity_id: light.yeelight_color2_7c49eb1566bb
      transition: 1
      brightness: 3
    service: light.turn_on
  - data:
      entity_id: light.yeelight_color2_7c49eb1566bb
      mode: normal
    service: light.yeelight_set_mode
  - wait_template: '{% if states.binary_sensor.motion_sensor_158d0001e531e0.attributes[''No
      motion since''] | int >= 180 and states.binary_sensor.motion_sensor_158d0001e531e0.state
      == ''off'' %}True{% else %}False{% endif %}'
  - condition: state
    entity_id: light.yeelight_color2_7c49eb1566bb
    state: 'on'
  - data:
      entity_id: light.yeelight_color2_7c49eb1566bb
      transition: 1
    service: light.turn_off
- id: '1541327330757'
  alias: Hall - empty room
  trigger:
  - platform: template
    value_template: '{% if states.binary_sensor.motion_sensor_158d0001e531e0.attributes[''No
      motion since''] | int >= 600 and states.binary_sensor.motion_sensor_158d0001e531e0.state
      == ''off'' %}True{% else %}False{% endif %}'
  condition:
  - condition: state
    entity_id: light.yeelight_color2_7c49eb1566bb
    state: 'on'
  action:
  - data:
      entity_id: light.yeelight_color2_7c49eb1566bb
      transition: 1
    service: light.turn_off
- id: '1541327802282'
  alias: Living room - stair LEDs
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e4707c
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.yeelight_strip_7811dc691c74
    state: 'off'
  - below: '50'
    condition: numeric_state
    entity_id: sensor.illumination_158d0001e4707c
  action:
  - data:
      entity_id: light.yeelight_strip_7811dc691c74
    service: light.turn_on
  - data:
      entity_id: light.yeelight_strip_7811dc691c74
      mode: normal
    service: light.yeelight_set_mode
  - wait_template: '{% if states.binary_sensor.motion_sensor_158d0001e4707c.attributes[''No
      motion since''] | int >= 120 and states.binary_sensor.motion_sensor_158d0001e4707c.state
      == ''off'' %}True{% else %}False{% endif %}'
  - condition: state
    entity_id: light.yeelight_strip_7811dc691c74
    state: 'on'
  - data:
      entity_id: light.yeelight_strip_7811dc691c74
    service: light.turn_off
- id: '1541328487535'
  alias: Living room - empty room
  trigger:
  - platform: template
    value_template: '{% if states.binary_sensor.motion_sensor_158d0001e43ac7.attributes[''No
      motion since''] | int >= 900 and states.binary_sensor.motion_sensor_158d0001e43ac7.state
      == ''off'' %}True{% else %}False{% endif %}'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.xiaomi_philips_ceiling_light
      state: 'on'
    - condition: state
      entity_id: light.yeelight_strip_7811dca220d2
      state: 'on'
    - condition: state
      entity_id: light.yeelight_strip_7811dc691c74
      state: 'on'
    - condition: state
      entity_id: switch.plug_158d0001deb419
      state: 'on'
    - condition: state
      entity_id: switch.plug_158d0001de79e6
      state: 'on'
  action:
  - data:
      entity_id: light.xiaomi_philips_ceiling_light
      transition: 1
    service: light.turn_off
  - data:
      entity_id: light.yeelight_strip_7811dca220d2
      transition: 1
    service: light.turn_off
  - data:
      entity_id: light.yeelight_strip_7811dc691c74
      transition: 1
    service: light.turn_off
  - data:
      entity_id: switch.plug_158d0001deb419
    service: switch.turn_off
  - data:
      entity_id: switch.plug_158d0001de79e6
    service: switch.turn_off
- id: '1541522658112'
  alias: Attic - entry area motion
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e547ae
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '30'
    condition: numeric_state
    entity_id: sensor.illumination_158d0001e547ae
  action:
  - data:
      entity_id: light.yeelight_color2_7c49eb1581f6
      transition: 1
      brightness: 255
    service: light.turn_on
  - data:
      entity_id: light.yeelight_color2_7c49eb1581f6
      mode: normal
    service: light.yeelight_set_mode
  - data:
      entity_id: light.yeelight_color2_04cf8c7bf9ba
      transition: 1
      brightness: 255
    service: light.turn_on
  - data:
      entity_id: light.yeelight_color2_04cf8c7bf9ba
      mode: normal
    service: light.yeelight_set_mode
  - wait_template: '{% if states.binary_sensor.motion_sensor_158d0001e547ae.attributes[''No
      motion since''] | int >= 180 and states.binary_sensor.motion_sensor_158d0001e547ae.state
      == ''off'' %}True{% else %}False{% endif %}'
  - condition: state
    entity_id: light.yeelight_color2_7c49eb1581f6
    state: 'on'
  - data:
      entity_id: light.yeelight_color2_7c49eb1581f6
      transition: 1
    service: light.turn_off
  - condition: state
    entity_id: light.yeelight_color2_04cf8c7bf9ba
    state: 'on'
  - data:
      entity_id: light.yeelight_color2_04cf8c7bf9ba
      transition: 1
    service: light.turn_off
- id: '1541525021925'
  alias: Attic - wardrobe area motion
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e55ff7
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: light.yeelight_color2_04cf8c7cc6ad
      transition: 1
    service: light.turn_on
  - data:
      entity_id: light.yeelight_color2_04cf8c7cc6ad
      mode: normal
    service: light.yeelight_set_mode
  - wait_template: '{% if states.binary_sensor.motion_sensor_158d0001e55ff7.attributes[''No
      motion since''] | int >= 180 and states.binary_sensor.motion_sensor_158d0001e55ff7.state
      == ''off'' %}True{% else %}False{% endif %}'
  - condition: state
    entity_id: light.yeelight_color2_04cf8c7cc6ad
    state: 'on'
  - data:
      entity_id: light.yeelight_color2_04cf8c7cc6ad
      transition: 1
    service: light.turn_off
- id: '1541876800870'
  alias: Attic - empty room
  trigger:
  - platform: template
    value_template: '{% if states.binary_sensor.motion_sensor_158d0001e547ae.attributes[''No
      motion since''] | int >= 300 and states.binary_sensor.motion_sensor_158d0001e43ac7.state
      == ''off'' and states.binary_sensor.motion_sensor_158d0001e55ff7.attributes[''No
      motion since''] | int >= 300 and states.binary_sensor.motion_sensor_158d0001e55ff7.state
      == ''off''%}True{% else %}False{% endif %}'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.yeelight_color2_7c49eb1581f6
      state: 'on'
    - condition: state
      entity_id: light.yeelight_color2_04cf8c7bf9ba
      state: 'on'
    - condition: state
      entity_id: light.yeelight_color2_04cf8c7cc6ad
      state: 'on'
  action:
  - data:
      entity_id: light.yeelight_color2_7c49eb1581f6
      transition: 1
    service: light.turn_off
  - data:
      entity_id: switch.plug_158d0001deb419
    service: switch.turn_off
- id: '1542048714041'
  alias: Guest room - motion
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e532dc
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.xiaomi_philips_e14_crystal
    state: 'off'
  - condition: state
    entity_id: light.xiaomi_philips_e14_crystal_2
    state: 'off'
  - below: '30'
    condition: numeric_state
    entity_id: sensor.illumination_158d0001e532dc
  action:
  - data:
      entity_id: light.xiaomi_philips_e14_crystal
      transition: 1
    service: light.turn_on
  - data:
      entity_id: light.xiaomi_philips_e14_crystal_2
      transition: 1
    service: light.turn_on
  - data:
      entity_id: light.xiaomi_philips_e14_crystal
      scene: 2
    service: light.xiaomi_miio_set_scene
  - data:
      entity_id: light.xiaomi_philips_e14_crystal_2
      scene: 2
    service: light.xiaomi_miio_set_scene
  - wait_template: '{% if states.binary_sensor.motion_sensor_158d0001e532dc.attributes[''No
      motion since''] | int >= 120 and states.binary_sensor.motion_sensor_158d0001e532dc.state
      == ''off'' %}True{% else %}False{% endif %}'
  - data:
      entity_id: light.xiaomi_philips_e14_crystal
      transition: 1
    service: light.turn_off
  - data:
      entity_id: light.xiaomi_philips_e14_crystal_2
      transition: 1
    service: light.turn_off
- id: '1542050718235'
  alias: Guest room - toogle light
  trigger:
  - event_data:
      entity_id: binary_sensor.switch_158d0001b182db
      click_type: single
    event_type: xiaomi_aqara.click
    platform: event
  - event_data:
      entity_id: binary_sensor.switch_158d0001be5b10
      click_type: single
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.xiaomi_philips_e14_crystal
      transition: 1
    service: light.toggle
  - data:
      entity_id: light.xiaomi_philips_e14_crystal_2
      transition: 1
    service: light.toggle
- id: '1542053124048'
  alias: Guest room - bright mode
  trigger:
  - event_data:
      entity_id: binary_sensor.switch_158d0001b182db
      click_type: hold
    event_type: xiaomi_aqara.click
    platform: event
  - event_data:
      entity_id: binary_sensor.switch_158d0001be5b10
      click_type: hold
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.xiaomi_philips_e14_crystal
    service: scene.turn_on
  - data:
      entity_id: light.xiaomi_philips_e14_crystal_2
    service: scene.turn_on
  - data:
      entity_id: light.xiaomi_philips_e14_crystal
      scene: 1
    service: light.xiaomi_miio_set_scene
  - data:
      entity_id: light.xiaomi_philips_e14_crystal_2
      scene: 1
    service: light.xiaomi_miio_set_scene
- id: '1543665916713'
  alias: Living room - bright enough
  trigger:
  - above: '120'
    entity_id: sensor.illumination_158d0001e43ac7
    platform: numeric_state
    for:
      minutes: 2
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.xiaomi_philips_ceiling_light
      state: 'on'
    - condition: state
      entity_id: light.yeelight_strip_7811dca220d2
      state: 'on'
    - condition: state
      entity_id: light.yeelight_strip_7811dc691c74
      state: 'on'
    - condition: state
      entity_id: switch.plug_158d0001deb419
      state: 'on'
  action:
  - service: tts.google_say
    entity_id: media_player.googlehome8282
    data:
      message: "Looks like it's sunny - turning the lights off."
      language: 'en-us'
  - data:
      entity_id: light.xiaomi_philips_ceiling_light
      transition: 1
    service: light.turn_off
  - data:
      entity_id: light.yeelight_strip_7811dca220d2
      transition: 1
    service: light.turn_off
  - data:
      entity_id: switch.plug_158d0001deb419
    service: switch.turn_off
- id: '1543859792965'
  alias: Tosia room light
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0002b85113
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.yeelight_color2_7c49eb1582dd
    state: 'off'
  - condition: state
    entity_id: switch.plug_158d0001ded32d
    state: 'off'
  - below: '10'
    condition: numeric_state
    entity_id: sensor.illumination_158d0002b85113
  - condition: time
    after: '15:00:00'
    before: '20:00:00'
  action:
  - data:
      entity_id: light.yeelight_color2_7c49eb1582dd
      transition: 1
      brightness: 15
      rgb_color:
      - 255
      - 0
      - 255
    service: light.turn_on
  - data:
      entity_id: light.yeelight_color2_7c49eb1566bb
      mode: rgb
    service: light.yeelight_set_mode
  - data:
      entity_id: switch.plug_158d0001ded32d
    service: switch.turn_on
  - wait_template: '{% if states.binary_sensor.motion_sensor_158d0002b85113.attributes[''No
      motion since''] | int >= 120 and states.binary_sensor.motion_sensor_158d0002b85113.state
      == ''off'' %}True{% else %}False{% endif %}'
  - condition: state
    entity_id: light.yeelight_color2_7c49eb1582dd
    state: 'on'
  - data:
      entity_id: light.yeelight_color2_7c49eb1582dd
    service: light.turn_off
  - data:
      entity_id: switch.plug_158d0001ded32d
    service: switch.turn_off
- id: '1544955116908'
  alias: Tosia toggle lamp
  trigger:
  - event_data:
      entity_id: binary_sensor.switch_158d0001b1827e
      click_type: single
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.yeelight_color2_7c49eb1582dd
      transition: 1
    service: light.toggle
- id: '1544955175467'
  alias: Tosia toggle Christmas tree
  trigger:
  - event_data:
      entity_id: binary_sensor.switch_158d0001b1827e
      click_type: double
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.plug_158d0001ded32d
    service: switch.toggle
- id: '1544967617743'
  alias: Leaving home
  trigger:
  - event_data:
      entity_id: binary_sensor.switch_158d00019d5813
      click_type: long_click_press
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - service: tts.google_say
    entity_id: media_player.googlehome8282
    data:
      message: 'See you later, turning the lights off.'
      language: 'en-us'
  - delay: 00:00:02
  - data:
      entity_id: scene.leaving_home
    service: scene.turn_on
- id: '1544970728739'
  alias: Coming home
  trigger:
  - event_data:
      entity_id: binary_sensor.switch_158d00019d5813
      click_type: single
    event_type: xiaomi_aqara.click
    platform: event
  condition: []
  action:
  - service: tts.google_say
    entity_id: media_player.googlehome8282
    data:
      message: 'Welcome home!'
      language: 'en-us'
  - data:
      entity_id: scene.living_room_normal
    service: scene.turn_on
  - data:
      entity_id: light.yeelight_color2_7c49eb1566bb
      transition: 1
      brightness: 230
    service: light.turn_on
  - data:
      entity_id: light.yeelight_strip_7811dc68588d
      transition: 1
    service: light.turn_on
