homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.009
  longitude: 19.961
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 269
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml
  # Customize entities matching a pattern
  customize_glob:
    "sensor.illumination_*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.pressure_*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.wall_switch*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.cube*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.motion_sensor*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.switch*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "automation.*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "scene.*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "script.*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.*_pm_2_5":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "media_player.*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.rtac68u_packet*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.rtac68u_byte*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# 12 characters MAC can be obtained from the gateway.
xiaomi_aqara:
  gateways:
    - mac: 34:CE:00:FB:56:E8
      key: 4z31ifz2sfrfv9mb
    - mac: 34:CE:00:88:A5:79
      key: iquhed73jeqsevke

light:
  - platform: xiaomi_miio
    name: Xiaomi Philips Ceiling Light
    host: 192.168.1.84
    token: 3d5f7ae53b51aa312e464b150b37453b
    model: philips.light.ceiling
  - platform: xiaomi_miio
    name: Xiaomi Philips E14 Frosted
    host: 192.168.1.107
    token: c1ac97f17b98eb0cc6132fd6f6433f91
    model: philips.light.candle2
  - platform: xiaomi_miio
    name: Xiaomi Philips E14 Crystal
    host: 192.168.1.52
    token: 52c93cf48a74c69378780cd800b4f430
    model: philips.light.candle2
  - platform: xiaomi_miio
    name: Xiaomi Philips E14 Crystal 2
    host: 192.168.1.116
    token: c16d7777b418c34a8e110f0a3614aa2a
    model: philips.light.candle2


vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.85
    token: 497847376161734438336f4a4b544f6d

# Full configuration.yaml entry
history_graph:
  windows:
    name: Windows open?
    entities:
      - binary_sensor.door_window_sensor_158d00023709f7
      - binary_sensor.door_window_sensor_158d0001ad5eb6
      - binary_sensor.door_window_sensor_158d00022f148a
      - binary_sensor.door_window_sensor_158d000232db84
      - binary_sensor.door_window_sensor_158d000232da46
      - binary_sensor.door_window_sensor_158d0002436b09
    hours_to_show: 24
    refresh: 60
  temperatures:
    name: Temperature
    entities:
      - sensor.temperature_158d0001b9208d
      - sensor.temperature_158d0001b92092
      - sensor.temperature_158d0001b92145
      - sensor.temperature_158d0001b1c3fb
      - sensor.temperature_158d00023208a6
      - sensor.temperature_158d0002320de3
      - sensor.temperature_158d0002320e0c
    hours_to_show: 24
    refresh: 60
  humidity:
    name: Humidity
    entities:
      - sensor.humidity_158d0001b9208d
      - sensor.humidity_158d0001b92092
      - sensor.humidity_158d0001b92145
      - sensor.humidity_158d0001b1c3fb
      - sensor.humidity_158d00023208a6
      - sensor.humidity_158d0002320de3
      - sensor.humidity_158d0002320e0c
    hours_to_show: 24
    refresh: 60
  pollution:
    name: Air pollution
    entities:
      - sensor.waqi_kurdwanow_krakow_maopolska_poland
      - sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland
      - sensor.waqi_skawina_maopolska_poland
    hours_to_show: 72
    refresh: 60
  illumination:
    name: Illumination
    entities:
      - sensor.illumination_158d0001e43ac7
      - sensor.illumination_158d0001e43bc7
      - sensor.illumination_158d0001e4707c
      - sensor.illumination_158d0001e531e0
      - sensor.illumination_158d0001e532dc
      - sensor.illumination_158d0001e547ae
      - sensor.illumination_158d0001e55ff7
      - sensor.illumination_34ce0088a579
      - sensor.illumination_34ce00fb56e8
    hours_to_show: 12
    refresh: 60

sensor:
  - platform: speedtest
    minute:
      - 0
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: waqi
    token: 036fe576f6536b92530a9d165825a52369ee4c76
    locations:
      - Kurdwanów, Kraków, Małopolska
      - Aleja Krasińskiego, Kraków, Małopolska
      - Skawina, Małopolska
  - platform: mold_indicator
    indoor_temp_sensor: sensor.temperature_158d00023208a6
    indoor_humidity_sensor: sensor.humidity_158d00023208a6
    outdoor_temp_sensor: sensor.temperature_158d0001b9208d
    calibration_factor: 2.0
  - platform: template
    sensors:
      waqi_kurdwanow_krakow_maopolska_poland_pm_2_5:
        friendly_name: "Kurdwanów PM 2.5"
        value_template: "{{ states.sensor.waqi_kurdwanow_krakow_maopolska_poland.attributes.pm_2_5 }}"
        unit_of_measurement: 'µg/m³'
        icon_template: 'mdi:cloud-outline'
        entity_id: sensor.waqi_kurdwanow_krakow_maopolska_poland
      waqi_kurdwanow_krakow_maopolska_poland_pm_10:
        friendly_name: "Kurdwanów PM 10"
        value_template: "{{ states.sensor.waqi_kurdwanow_krakow_maopolska_poland.attributes.pm_10 }}"
        unit_of_measurement: 'µg/m³'
        icon_template: 'mdi:cloud-outline'
        entity_id: sensor.waqi_kurdwanow_krakow_maopolska_poland
      waqi_aleja_krasinskiego_krakow_maopolska_poland_pm_2_5:
        friendly_name: "Aleje PM 2.5"
        value_template: "{{ states.sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland.attributes.pm_2_5 }}"
        unit_of_measurement: 'µg/m³'
        icon_template: 'mdi:cloud-outline'
        entity_id: sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland
      waqi_aleja_krasinskiego_krakow_maopolska_poland_pm_10:
        friendly_name: "Aleje PM 10"
        value_template: "{{ states.sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland.attributes.pm_10 }}"
        unit_of_measurement: 'µg/m³'
        icon_template: 'mdi:cloud-outline'
        entity_id: sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland
      waqi_skawina_maopolska_poland_pm_2_5:
        friendly_name: "Skawina PM 2.5"
        value_template: "{{ states.sensor.waqi_skawina_maopolska_poland.attributes.pm_2_5 }}"
        unit_of_measurement: 'µg/m³'
        icon_template: 'mdi:cloud-outline'
        entity_id: sensor.waqi_skawina_maopolska_poland
      waqi_skawina_maopolska_poland_pm_10:
        friendly_name: "Skawina PM 10"
        value_template: "{{ states.sensor.waqi_skawina_maopolska_poland.attributes.pm_10 }}"
        unit_of_measurement: 'µg/m³'
        icon_template: 'mdi:cloud-outline'
        entity_id: sensor.waqi_skawina_maopolska_poland

device_tracker:
  - platform: asuswrt
    host: 192.168.1.254
    username: wojtek
    ssh_key: /home/homeassistant/.homeassistant/id_rsa
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false

weather:
  - platform: yweather
    name: Kraków

sun:

scene:
  - name: Living room normal
    entities:
        light.xiaomi_philips_ceiling_light:
            state: on
            transition: 5
            brightness_pct: 65
        light.yeelight_strip_7811dca220d2:
            state: on
            transition: 5
            brightness_pct: 100
            rgb_color: [255,205,166]
  - name: Living room slight dim
    entities:
        light.xiaomi_philips_ceiling_light:
            state: on
            transition: 5
            brightness_pct: 50
        light.yeelight_strip_7811dca220d2:
            state: on
            transition: 5
            brightness_pct: 100
            rgb_color: [255,205,166]
  - name: Living room evening
    entities:
        light.xiaomi_philips_ceiling_light:
            state: on
            transition: 5
            brightness_pct: 35
        light.yeelight_strip_7811dca220d2:
            state: on
            transition: 5
            brightness_pct: 100
            rgb_color: [255,205,166]
  - name: Living room TV mode
    entities:
        light.xiaomi_philips_ceiling_light: off
        light.yeelight_strip_7811dca220d2:
            state: on
            transition: 5
            brightness_pct: 90
            rgb_color: [255,205,166]
  - name: Hall light day
    entities:
        light.yeelight_color2_7c49eb1566bb:
            state: on
            transition: 1
            brightness_pct: 100
  - name: Hall light night
    entities:
        light.yeelight_color2_7c49eb1566bb:
            state: on
            transition: 1
            brightness_pct: 10
  - name: Guest room lights
    entities:
        light.xiaomi_philips_e14_crystal:
            state: on
            transition: 1
            brightness_pct: 100
        light.xiaomi_philips_e14_crystal_2:
            state: on
            transition: 1
            brightness_pct: 100
        switch.plug_158d0001ded32d:
            state: on
