homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.009
  longitude: 19.961
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 269
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml
  # Customize entities matching a pattern
  customize_glob:
    "sensor.illumination_*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.pressure_*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.wall_switch*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.cube*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.motion_sensor*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.switch*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "automation.*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "scene.*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "script.*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.*_pm_2_5":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "media_player.*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.rtac68u_packet*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.rtac68u_byte*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "group.all_switches":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true"
    "group.all_devices":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true"

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: jaskrowo.asuscomm.com:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

map:
owntracks:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# 12 characters MAC can be obtained from the gateway.
xiaomi_aqara:
  gateways:
    - mac: 34:CE:00:FB:56:E8
      key: 4z31ifz2sfrfv9mb
    - mac: 34:CE:00:88:A5:79
      key: iquhed73jeqsevke

light:
  - platform: xiaomi_miio
    name: Xiaomi Philips Ceiling Light
    host: 192.168.1.84
    token: 3d5f7ae53b51aa312e464b150b37453b
    model: philips.light.ceiling
  - platform: xiaomi_miio
    name: Master bedroom bed lamp
    host: 192.168.1.107
    token: c1ac97f17b98eb0cc6132fd6f6433f91
    model: philips.light.candle2
  - platform: xiaomi_miio
    name: Xiaomi Philips E14 Crystal
    host: 192.168.1.52
    token: 52c93cf48a74c69378780cd800b4f430
    model: philips.light.candle2
  - platform: xiaomi_miio
    name: Xiaomi Philips E14 Crystal 2
    host: 192.168.1.116
    token: c16d7777b418c34a8e110f0a3614aa2a
    model: philips.light.candle2
  - platform: xiaomi_miio
    name: Tosia left wall lamp
    host: 192.168.1.118
    token: 11f0e1c5e69ec2ca7b19833d642e8a82
    model: philips.light.candle2

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.85
    token: 497847376161734438336f4a4b544f6d

# Full configuration.yaml entry
history_graph:
  windows:
    name: Windows open?
    entities:
      - binary_sensor.door_window_sensor_158d00023709f7
      - binary_sensor.door_window_sensor_158d0001ad5eb6
      - binary_sensor.door_window_sensor_158d00022f148a
      - binary_sensor.door_window_sensor_158d000232db84
      - binary_sensor.door_window_sensor_158d000232da46
      - binary_sensor.door_window_sensor_158d0002436b09
    hours_to_show: 24
    refresh: 60
  temperatures:
    name: Temperature
    entities:
      - sensor.temperature_158d0001b9208d
      - sensor.temperature_158d0001b92092
      - sensor.temperature_158d0001b92145
      - sensor.temperature_158d0001b1c3fb
      - sensor.temperature_158d00023208a6
      - sensor.temperature_158d0002320de3
      - sensor.temperature_158d0002320e0c
    hours_to_show: 24
    refresh: 60
  humidity:
    name: Humidity
    entities:
      - sensor.humidity_158d0001b9208d
      - sensor.humidity_158d0001b92092
      - sensor.humidity_158d0001b92145
      - sensor.humidity_158d0001b1c3fb
      - sensor.humidity_158d00023208a6
      - sensor.humidity_158d0002320de3
      - sensor.humidity_158d0002320e0c
    hours_to_show: 24
    refresh: 60
  pollution:
    name: Air pollution
    entities:
      - sensor.waqi_kurdwanow_krakow_maopolska_poland
      - sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland
      - sensor.waqi_skawina_maopolska_poland
    hours_to_show: 72
    refresh: 60
  illumination:
    name: Illumination
    entities:
      - sensor.illumination_158d0001e43ac7
      - sensor.illumination_158d0001e43bc7
      - sensor.illumination_158d0001e4707c
      - sensor.illumination_158d0001e531e0
      - sensor.illumination_158d0001e532dc
      - sensor.illumination_158d0001e547ae
      - sensor.illumination_158d0001e55ff7
    hours_to_show: 12
    refresh: 60

sensor: !include sensors.yaml

asuswrt:
  host: 192.168.1.254
  username: wojtek
  ssh_key: "/config/id_rsa"

weather:
  - platform: met

sun:

lovelace:
  mode: yaml

# Example configuration.yaml entry
circadian_lighting:
  max_colortemp: 5500
  min_colortemp: 3000
  sunrise_offset: "00:00:00"
  sunset_offset: "00:00:00"

switch:
  - platform: circadian_lighting
    name: "Living room auto ceiling"
    max_brightness: 50
    lights_ct:
      - light.xiaomi_philips_ceiling_light
  - platform: circadian_lighting
    name: "Living room auto LEDs"
    lights_ct:
      - light.yeelight_strip_7811dca220d2
      - light.yeelight_strip_7811dc691c74
  - platform: circadian_lighting
    name: "Hall lights auto"
    lights_ct:
      - light.yeelight_color2_7c49eb1566bb
  - platform: circadian_lighting
    name: "Guest room lights auto"
    min_brightness: 50
    lights_ct:
      - light.xiaomi_philips_e14_crystal
      - light.xiaomi_philips_e14_crystal_2
  - platform: circadian_lighting
    name: "Master bedroom lights auto"
    lights_ct:
      - light.master_bedroom_bed_lamp
    lights_rgb:
      - light.gateway_light_34ce00fb56e8
    lights_brightness:
      - light.yeelight_strip_7811dc66f063
  - platform: circadian_lighting
    name: "Attic lights auto"
    lights_ct:
      - light.yeelight_color2_7c49eb1581f6
      - light.yeelight_color2_04cf8c7bf9ba
      - light.yeelight_color2_04cf8c7cc6ad
  - platform: circadian_lighting
    name: "Kitchen lights auto"
    min_brightness: 90
    lights_ct:
      - light.yeelight_strip_7811dc68588d
    lights_rgb:
      - light.gateway_light_34ce0088a579
  - platform: circadian_lighting
    name: "Tosia room lights auto"
    max_brightness: 50
    lights_ct:
      - light.yeelight_color2_04cf8c7cb0ca
      - light.tosia_left_wall_lamp
    lights_brightness:
      - light.yeelight_color2_7c49eb1582dd

scene:
  - name: Living room day
    entities:
        light.xiaomi_philips_ceiling_light: on
        light.yeelight_strip_7811dca220d2: off
        switch.plug_158d0001deb419: off
        switch.plug_158d0001de79e6: off
  - name: Living room evening
    entities:
        light.xiaomi_philips_ceiling_light: on
        light.yeelight_strip_7811dca220d2: on
        switch.plug_158d0001deb419: on
        switch.plug_158d0001de79e6: on
  - name: Living room TV mode
    entities:
        light.xiaomi_philips_ceiling_light: off
        light.yeelight_strip_7811dca220d2: on
        switch.plug_158d0001deb419: on
        switch.plug_158d0001de79e6: on

# To start the camera:
# pi@hassbian:~/videoP2Proxy $ videop2proxy --ip 192.168.1.125 --token 34313335586f726f5657486476357663 --rtsp 8554
camera:
 - platform: ffmpeg
   input: -rtsp_transport tcp -i rtsp://127.0.0.1:8554/
