homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret geo_latitude
  longitude: !secret geo_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 269
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  packages: !include_dir_named packages
  # Customization file
  customize: !include customize.yaml
  # Customize entities matching a pattern
  customize_glob:
    "sensor.illumination_*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.pressure_*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.wall_switch*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.cube*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.motion_sensor*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "binary_sensor.switch*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "automation.*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "scene.*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "script.*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.*_pm_2_5":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "media_player.*":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.rtac68u_packet*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "sensor.rtac68u_byte*":
      hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
    "group.all_switches":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true"
    "group.all_devices":
      hidden: false
      homebridge_hidden: true
      emulated_hue_hidden: true"
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      trusted_users:
        192.168.1.103: 8d9bb01c879f4b8abcb4e1fee53a6a21
        192.168.1.2: 8d9bb01c879f4b8abcb4e1fee53a6a21
      allow_bypass_login: true

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

http:
  base_url: https://t8rvacetnpv7de2kvwrbusxxhurmyci8.ui.nabu.casa
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: https://jaskrowo.asuscomm.com
  # server_port: 443
  # ssl_certificate: /config/cert.pem
  # ssl_key: /config/key.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

yeelight:
  devices:
    192.168.1.33:
      name: Downstairs hall lamp
    192.168.1.34:
      name: Wall LEDs
    192.168.1.35:
      name: Stove LEDs
    192.168.1.36:
      name: Spare light 1
    192.168.1.37:
      name: Stairs LEDs
    192.168.1.39:
      name: Right wall lamp
    192.168.1.38:
      name: Bed LEDs
    192.168.1.40:
      name: Tosia lamp
    # 192.168.1.41:
    #   name: Attic left light
    # 192.168.1.42:
    #   name: Attic right light
    # 192.168.1.43:
    #   name: Attic wardrobe area light

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Text to speech
tts:
  - platform: google_translate
    language: "pl"

# Cloud
cloud:

map:
owntracks:

automation: !include automations.yaml
script: !include scripts.yaml

# 12 characters MAC can be obtained from the gateway.
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: 34:CE:00:FB:56:E8
      key: 4z31ifz2sfrfv9mb

light:
  - platform: xiaomi_miio
    name: Xiaomi Philips Ceiling Light
    host: 192.168.1.21
    token: 3d5f7ae53b51aa312e464b150b37453b
    model: philips.light.ceiling
  - platform: xiaomi_miio
    name: Master bedroom bed lamp
    host: 192.168.1.22
    token: c1ac97f17b98eb0cc6132fd6f6433f91
    model: philips.light.candle2
  - platform: xiaomi_miio
    name: Xiaomi Philips E14 Crystal
    host: 192.168.1.23
    token: 52c93cf48a74c69378780cd800b4f430
    model: philips.light.candle2
  - platform: xiaomi_miio
    name: Xiaomi Philips E14 Crystal 2
    host: 192.168.1.24
    token: c16d7777b418c34a8e110f0a3614aa2a
    model: philips.light.candle2
  # - platform: xiaomi_miio
  #   name: Tosia left wall lamp
  #   host: 192.168.1.25
  #   token: 11f0e1c5e69ec2ca7b19833d642e8a82
  #   model: philips.light.candle2
  - platform: xiaomi_miio
    name: Wardrobe lamp
    host: 192.168.1.26
    token: 641353095386f5057a1243c1f0c11a3d
    model: philips.light.downlight
  - platform: xiaomi_miio
    name: Upstairs hall left lamp
    host: 192.168.1.27
    token: 6be52caebc5d6f6794b5e8df1fe1983c
    model: philips.light.downlight
  - platform: xiaomi_miio
    name: Upstairs hall right lamp
    host: 192.168.1.28
    token: 9077b63fbca71504a06c0441906260c9
    model: philips.light.downlight
  - platform: xiaomi_miio
    name: Downstairs bathroom side lamp
    host: 192.168.1.50
    token: 49e966e4a479ba532d5a3763a3de7da4
    model: philips.light.downlight

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.29
    token: "616e4e30556767583138707636386345"

# Full configuration.yaml entry
history_graph:
  windows:
    name: Windows open?
    entities:
      - binary_sensor.0x00158d00023709f7_contact
      - binary_sensor.0x00158d0001ad5eb6_contact
      - binary_sensor.0x00158d00022f148a_contact
      - binary_sensor.0x00158d000232db84_contact
      - binary_sensor.0x00158d000232da46_contact
      - binary_sensor.0x00158d0002436b09_contact
    hours_to_show: 24
    refresh: 60
  temperatures:
    name: Temperature
    entities:
      - sensor.0x00158d0001b9208d_temperature
      - sensor.0x00158d0001b92145_temperature
      - sensor.0x00158d0001b1c3fb_temperature
      - sensor.0x00158d00023208a6_temperature
      - sensor.0x00158d0002320de3_temperature
      - sensor.0x00158d0002320e0c_temperature
    hours_to_show: 24
    refresh: 60
  humidity:
    name: Humidity
    entities:
      - sensor.0x00158d0001b9208d_humidity
      - sensor.0x00158d0001b92145_humidity
      - sensor.0x00158d0001b1c3fb_humidity
      - sensor.0x00158d00023208a6_humidity
      - sensor.0x00158d0002320de3_humidity
      - sensor.0x00158d0002320e0c_humidity
    hours_to_show: 24
    refresh: 60
  pollution:
    name: Air pollution
    entities:
      - sensor.waqi_kurdwanow_krakow_maopolska_poland
      - sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland
      - sensor.waqi_skawina_maopolska_poland
    hours_to_show: 72
    refresh: 60
  illumination:
    name: Illumination
    entities:
      - sensor.0x00158d0001e43ac7_illuminance
      - sensor.0x00158d0001e43bc7_illuminance
      - sensor.0x00158d0001e4707c_illuminance
      - sensor.0x00158d0001e531e0_illuminance
      - sensor.0x00158d0001e532dc_illuminance
      - sensor.0x00158d0001e547ae_illuminance
      - sensor.0x00158d0001e55ff7_illuminance
    hours_to_show: 12
    refresh: 60

sensor: !include sensors.yaml

binary_sensor:
  - platform: trend
    sensors:
      outside_temperature_rising:
        entity_id: sensor.0x00158d0001b9208d_temperature
        sample_duration: 1200
        max_samples: 15
        min_gradient: 0.00055
  - platform: car_wash
    weather: weather.dark_sky

asuswrt:
  host: 192.168.1.254
  protocol: ssh
  username: wojtek
  ssh_key: "/config/id_rsa"
  sensors:
    - upload_speed
    - download_speed

device_tracker:
  - platform: asuswrt
    host: 192.168.1.254
    protocol: ssh
    username: wojtek
    ssh_key: "/config/id_rsa"
    new_device_defaults:
      track_new_devices: false

sun:

lovelace:
  mode: yaml

# Example configuration.yaml entry
circadian_lighting:
  max_colortemp: 5000
  min_colortemp: 3000
  sunrise_offset: "03:00:00"
  sunset_offset: "-00:45:00"

switch:
  # - platform: xiaomi_miio
  #   name: "Guest room floor lamp"
  #   host: 192.168.1.30
  #   token: c434a0a9b9897896e9b6abc1ffc80fa3
  # - platform: xiaomi_miio
  #   name: "Fan"
  #   host: 192.168.1.31
  #   token: 7d34b272ed27dfd6cf229a75ab5a7a47
  - platform: circadian_lighting
    name: "Living room auto ceiling"
    min_brightness: 30
    max_brightness: 70
    lights_ct:
      - light.xiaomi_philips_ceiling_light
  - platform: circadian_lighting
    name: "Living room auto LEDs"
    min_brightness: 35
    lights_ct:
      - light.stairs_leds
      - light.wall_leds
  - platform: circadian_lighting
    name: "Hall lights auto"
    lights_ct:
      - light.downstairs_hall_lamp
    min_brightness: 50
  - platform: circadian_lighting
    name: "Guest room lights auto"
    min_brightness: 50
    lights_ct:
      - light.xiaomi_philips_e14_crystal
      - light.xiaomi_philips_e14_crystal_2
  - platform: circadian_lighting
    name: "Master bedroom lights auto"
    lights_ct:
      - light.master_bedroom_bed_lamp
    lights_rgb:
      - light.gateway_light_34ce00fb56e8
    lights_brightness:
      - light.bed_leds
  - platform: circadian_lighting
    name: "Attic lights auto"
    min_brightness: 50
    lights_ct:
      - light.0x00158d0003fa55ab_light
      - light.attic_right_lamp_light
      - light.0x00158d000410f2db_light
  - platform: circadian_lighting
    name: "Downstairs bathroom ceiling light auto"
    min_brightness: 70
    lights_ct:
      - light.0x00158d0002c67ac3_light
  - platform: circadian_lighting
    name: "Downstairs bathroom side light auto"
    max_brightness: 50
    min_brightness: 30
    lights_ct:
      - light.downstairs_bathroom_side_lamp
  - platform: circadian_lighting
    name: "Kitchen lights auto"
    min_brightness: 90
    lights_ct:
      - light.stove_leds
  - platform: circadian_lighting
    name: "Tosia room lights auto"
    lights_ct:
      - light.tosia_lamp
      - light.0xec1bbdfffeb7fbbc_light
      - light.0x00158d0002b88c1c_light
  - platform: circadian_lighting
    name: "Wardrobe lights auto"
    lights_ct:
      - light.wardrobe_lamp
      - light.upstairs_hall_left_lamp
      - light.upstairs_hall_right_lamp
  - platform: circadian_lighting
    name: "IKEA Tradfri auto brightness"
    lights_brightness:
      - light.0xec1bbdfffeb7fbbc_light
scene:
  - name: Living room day
    entities:
      light.xiaomi_philips_ceiling_light: on
      light.wall_leds: off
  - name: Living room evening
    entities:
      light.xiaomi_philips_ceiling_light: on
      light.wall_leds: on
  - name: Living room TV mode
    entities:
      light.xiaomi_philips_ceiling_light: off
      light.wall_leds: on
  - name: Somebody sleeping in living room
    entities:
      automation.living_room_motion_01_normal: off
      automation.living_room_motion_02_evening: off
      automation.living_room_motion_03_tv_mode: off
      group.living_room_lights: off
      group.kitchen_lights: off
      group.dining_area: off
  - name: Living room normal mode
    entities:
      automation.living_room_motion_01_normal: on
      automation.living_room_motion_02_evening: on
      automation.living_room_motion_03_tv_mode: on
      switch.circadian_lighting_living_room_auto_ceiling: on
  - name: Wojtek is cycling
    entities:
      switch.circadian_lighting_guest_room_lights_auto: off
      switch.circadian_lighting_ikea_tradfri_auto_brightness: off
      automation.guest_room_motion: off
      light.xiaomi_philips_e14_crystal:
        state: on
        brightness: 3
      light.xiaomi_philips_e14_crystal_2: off
      fan.xiaomi_smart_fan: on
      switch.0x00158d00039e5eb1_switch: on
  - name: Wojtek finished cycling
    entities:
      switch.circadian_lighting_guest_room_lights_auto: on
      switch.circadian_lighting_ikea_tradfri_auto_brightness: on
      automation.guest_room_motion: on
      light.xiaomi_philips_e14_crystal: on
      light.xiaomi_philips_e14_crystal_2: on
      fan.xiaomi_smart_fan: off
      switch.0x00158d00039e5eb1_switch: off

camera:
  - platform: generic
    name: yi-hack-01
    still_image_url: http://192.168.1.49:8080/cgi-bin/snapshot.sh
    stream_source: rtsp://192.168.1.49/ch0_0.h264
    verify_ssl: false
  - platform: generic
    name: yi-hack-02
    still_image_url: http://192.168.1.51:8080/cgi-bin/snapshot.sh
    stream_source: rtsp://192.168.1.51/ch0_0.h264
    verify_ssl: false
  - platform: generic
    name: yi-hack-03
    still_image_url: http://192.168.1.52:8080/cgi-bin/snapshot.sh
    stream_source: rtsp://192.168.1.52/ch0_0.h264
    verify_ssl: false

# To start the camera:
# pi@hassbian:~/videoP2Proxy $ videop2proxy --ip 192.168.1.125 --token 34313335586f726f5657486476357663 --rtsp 8554
#   - platform: ffmpeg
#     input: -rtsp_transport tcp -i rtsp://127.0.0.1:8554/
#     extra_arguments: -pred 1 -q:v 2

stream:
#
# image_processing:
#   - platform: deepstack_face
#     ip_address: localhost
#     port: 5000
#     scan_interval: 60
#     source:
#       - entity_id: camera.ffmpeg
#         name: face_counter

notify:
  - platform: html5
    name: Home Assistant
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

media_player:
  - platform: denonavr
    host: 192.168.1.5
    name: Marantz SR5008
    show_all_sources: true

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

recorder:
  purge_keep_days: 3
  purge_interval: 1
  exclude:
    domains:
      - automation
      - weblink
      - updater

system_health:
speedtestdotnet:

fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.1.32
    token: b385299315ea59d2a71abe8ae112b744

group:
  kitchen_lights:
    name: Kitchen lights
    entities:
      - switch.shelly1_55df6e_relay_0
      - light.stove_leds
      - switch.0x00158d0003951e91_switch
  dining_area:
    name: Dining area
    entities:
      - switch.shelly2_5a4ada_relay_1
      - switch.shelly2_5a4ada_relay_0
  living_room_lights:
    name: Living room lights
    entities:
      - light.xiaomi_philips_ceiling_light
      - switch.shelly1_5556b7_relay_0
      - light.wall_leds
      # - switch.0x00158d0001de79e6_switch
      # - switch.fan
      - light.stairs_leds
      - light.downstairs_hall_lamp
      - switch.shelly1_554b82_relay_0
  downstairs_windows:
    name: Downstairs windows
    entities:
      - binary_sensor.0x00158d0001ad5eb6_contact
      - binary_sensor.0x00158d00023709f7_contact
      - binary_sensor.0x00158d00022f148a_contact
  downstairs_bathroom_lights:
    name: Downstairs bathroom lights
    entities:
      - light.0x00158d0002c67ac3_light
      - light.downstairs_bathroom_side_lamp
  tosia_bedroom_lights:
    name: Tosia's bedroom lights
    entities:
      - light.0xec1bbdfffeb7fbbc_light
      - light.0x00158d0002b88c1c_light
      - light.tosia_lamp
      # - switch.0x00158d0003951ef9_switch
  guest_room_lights:
    name: Guest room lights
    entities:
      - light.xiaomi_philips_e14_crystal
      - light.xiaomi_philips_e14_crystal_2
  upstairs_hall_lights:
    name: Upstairs hall lights
    entities:
      - light.upstairs_hall_left_lamp
      - light.upstairs_hall_right_lamp
  master_bedroom_lights:
    name: Master bedroom lights
    entities:
      - light.master_bedroom_bed_lamp
      - light.bed_leds
      - switch.shelly1_2c03c5_relay_0
      - switch.shelly1_55e273_relay_0
      - light.gateway_light_34ce00fb56e8

mqtt:
  broker: 172.17.0.1
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"

mobile_app:

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    code_arm_required: false
    pending_time: 10
    disarmed:
      trigger_time: 0
    triggered:
      pending_time: 0

zone:
  - name: Schibsted
    latitude: 50.073305
    longitude: 19.945491
    icon: mdi:office-building
    radius: 300
  - name: ABB
    latitude: 50.064151
    longitude: 19.960579
    icon: mdi:office-building
    radius: 300
  # This will override the default home zone
  - name: Home
    latitude: !secret geo_latitude
    longitude: !secret geo_longitude
    icon: mdi:home

python_script:

weather:
  - platform: darksky
    api_key: !secret darksky_key

webhook:

zigbee2mqtt_networkmap:
  #topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: "Zigbee Map"
    url: "/local/community/zigbee2mqtt_networkmap/map.html"
    icon: "mdi:zigbee"
