version: "3"
services:
  watchtower:
    container_name: "watchtower"
    image: v2tec/watchtower
    command: --schedule "0 0 1 * * 0" --cleanup --label-enable --debug
    restart: always
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2021.4.6
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
    labels:
      - com.centurylinklabs.watchtower.enable=true

  zigbee2mqtt:
    container_name: zigbee2mqtt
    # image: koenkk/zigbee2mqtt:1.14.0 # last stable version
    image: koenkk/zigbee2mqtt
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - mosquitto
