- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"
- platform: attributes
  friendly_name: "Batteries"
  attribute: battery_level
  unit_of_measurement: "%"
  entities:
    - device_tracker.mi_mix_2
    - device_tracker.wojtek_mimix2
    - device_tracker.mi_a2_lite
    - device_tracker.gosiak_mia2_2
    - device_tracker.wojtek_s_ipad
- platform: attributes
  friendly_name: "AC Power"
  attribute: power_consumption_power
  unit_of_measurement: "kW"
  entities:
    - climate.master_bedroom_ac
- platform: attributes
  friendly_name: "Airly CAQI"
  attribute: air_quality_index
  unit_of_measurement: "AQI"
  icon: "mdi:cloud"
  entities:
    - air_quality.airly
- platform: attributes
  friendly_name: "Airly description"
  attribute: advice
  entities:
    - air_quality.airly
- platform: template
  sensors:
    light_brightness_philips_ceiling_light:
      friendly_name: "Philips Ceiling light brightness"
      value_template: >-
        {%- if is_state('light.xiaomi_philips_ceiling_light', 'on') %}
            {{ (100 * states.light.xiaomi_philips_ceiling_light.attributes.brightness / 255) | round }}
        {% else %}
            0
        {%- endif %}
      icon_template: "mdi:brightness-6"
      entity_id: light.xiaomi_philips_ceiling_light
      device_class: illuminance
      unit_of_measurement: "%"
    light_ct_philips_ceiling_light:
      friendly_name: "Philips Ceiling light CT"
      value_template: >-
        {%- if is_state('light.xiaomi_philips_ceiling_light', 'on') %}
            {{ (100 * states.light.xiaomi_philips_ceiling_light.attributes.color_temp / states.light.xiaomi_philips_ceiling_light.attributes.max_mireds) | round }}
        {% else %}
            0
        {%- endif %}
      icon_template: "mdi:temperature-kelvin"
      entity_id: light.xiaomi_philips_ceiling_light
      unit_of_measurement: "%"
    light_brightness_hall_light:
      friendly_name: "Hall light brightness"
      value_template: >-
        {%- if is_state('light.yeelight_color2_7c49eb1566bb', 'on') %}
            {{ (100 * states.light.yeelight_color2_7c49eb1566bb.attributes.brightness / 255) | round }}
        {% else %}
            0
        {%- endif %}
      icon_template: "mdi:brightness-6"
      entity_id: light.yeelight_color2_7c49eb1566bb
      device_class: illuminance
      unit_of_measurement: "%"
    light_ct_hall_light:
      friendly_name: "Hall Light CT"
      value_template: >-
        {%- if is_state('light.yeelight_color2_7c49eb1566bb', 'on') %}
            {{ (states.light.yeelight_color2_7c49eb1566bb.attributes.color_temp / states.light.yeelight_color2_7c49eb1566bb.attributes.max_mireds) | round }}
        {% else %}
            0
        {%- endif %}
      icon_template: "mdi:temperature-kelvin"
      entity_id: light.yeelight_color2_7c49eb1566bb
      unit_of_measurement: "%"
- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
- platform: cpuspeed
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone2/temp"
  unit_of_measurement: "°C"
  value_template: "{{ (value | multiply(0.001)) | round(1) }}"
# - platform: google_travel_time
#   scan_interval: 600
#   api_key: AIzaSyAjBHHLSZ_3TeLhqhHXXY6Sq3RJRmODWZQ
#   origin: device_tracker.wiskra_mimix2_2
#   destination: Armii Krajowej 28, Kraków
#   options:
#     mode: driving
- platform: xiaomi_miio
  name: Xiaomi Air Quality Monitor
  host: 192.168.1.44
  token: dccf23c77edb2d19e4b827a49330f26f
- platform: attributes
  friendly_name: "Spotify source"
  icon: "mdi:spotify"
  attribute: source
  entities:
    - media_player.spotify_wojciech_iskra
- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
- platform: mqtt
  name: Zigbee2mqtt Networkmap
  # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
  state_topic: zigbee2mqtt/bridge/networkmap/raw
  value_template: >-
    {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
  # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
  json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw
- platform: zwift
  username: !secret my_zwift_username
  password: !secret my_zwift_password
  update_interval: 180
- platform: statistics
  entity_id: sensor.shelly_plug_s_51d92a_power_0_2
  name: washing_machine_power_stats
  sampling_size: 120
  precision: 0
  max_age:
    minutes: 60
