- platform: template
  sensors:
    battery_wiskra_mimix2:
      friendly_name: Wojtek's Mi Mix 2
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.wiskra_mimix2.attributes.battery %}
              {{ states.device_tracker.wiskra_mimix2.attributes.battery|round }}
          {% else %}
              {{ states.device_tracker.wiskra_mimix2.state }}
          {%- endif %}
      device_class: battery
    battery_gosiak_mia2:
      friendly_name: Gosiak's Mi A2 Lite
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.gosiak_mia2.attributes.battery %}
              {{ states.device_tracker.gosiak_mia2.attributes.battery|round }}
          {% else %}
              {{ states.device_tracker.gosiak_mia2.state }}
          {%- endif %}
      device_class: battery
    battery_wiskra_ipad:
      friendly_name: iPad
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.device_tracker.wojtek_1996c7e7_3ef9_451b_be55_5b27c09d3c5d.attributes.battery %}
              {{ states.device_tracker.wojtek_1996c7e7_3ef9_451b_be55_5b27c09d3c5d.attributes.battery|round }}
          {% else %}
              {{ states.device_tracker.wojtek_1996c7e7_3ef9_451b_be55_5b27c09d3c5d.state }}
          {%- endif %}
      device_class: battery
- platform: template
  sensors:
    light_brightness_philips_ceiling_light:
      friendly_name: "Philips Ceiling light brightness"
      value_template: >-
          {%- if is_state('light.xiaomi_philips_ceiling_light', 'on') %}
              {{ (100 * states.light.xiaomi_philips_ceiling_light.attributes.brightness / 255) | round }}
          {% else %}
              0
          {%- endif %}
      icon_template: 'mdi:brightness-6'
      entity_id: light.xiaomi_philips_ceiling_light
      device_class: illuminance
      unit_of_measurement: '%'
    light_ct_philips_ceiling_light:
      friendly_name: "Philips Ceiling light CT"
      value_template: >-
          {%- if is_state('light.xiaomi_philips_ceiling_light', 'on') %}
              {{ (100 * states.light.xiaomi_philips_ceiling_light.attributes.color_temp / states.light.xiaomi_philips_ceiling_light.attributes.max_mireds) | round }}
          {% else %}
              0
          {%- endif %}
      icon_template: 'mdi:temperature-kelvin'
      entity_id: light.xiaomi_philips_ceiling_light
      unit_of_measurement: '%'
    light_brightness_hall_light:
      friendly_name: "Hall light brightness"
      value_template: >-
          {%- if is_state('light.yeelight_color2_7c49eb1566bb', 'on') %}
              {{ (100 * states.light.yeelight_color2_7c49eb1566bb.attributes.brightness / 255) | round }}
          {% else %}
              0
          {%- endif %}
      icon_template: 'mdi:brightness-6'
      entity_id: light.yeelight_color2_7c49eb1566bb
      device_class: illuminance
      unit_of_measurement: '%'
    light_ct_hall_light:
      friendly_name: "Hall Light CT"
      value_template: >-
        {%- if is_state('light.yeelight_color2_7c49eb1566bb', 'on') %}
            {{ (states.light.yeelight_color2_7c49eb1566bb.attributes.color_temp / states.light.yeelight_color2_7c49eb1566bb.attributes.max_mireds) | round }}
        {% else %}
            0
        {%- endif %}
      icon_template: 'mdi:temperature-kelvin'
      entity_id: light.yeelight_color2_7c49eb1566bb
      unit_of_measurement: '%'
- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
- platform: cpuspeed
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone3/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'
- platform: airly
  api_key: !secret airly_api_key
  latitude: 49.87
  longitude: 19.497
- platform: airly
  api_key: !secret airly_api_key
- platform: airly
  api_key: !secret airly_api_key
  latitude: 50.0721293
  longitude: 19.8916957
- platform: xiaomi_miio
  name: Xiaomi Air Quality Monitor
  host: 192.168.1.64
  token: dccf23c77edb2d19e4b827a49330f26f
