title: Home
views:
  - title: Home
    path: default_view
    badges: []
    cards:
      - title: Living room
        entities:
          - sensor.temperature_158d0001b1c3fb
          - sensor.humidity_158d0001b1c3fb
          - binary_sensor.door_window_sensor_158d0001ad5eb6
          - light.xiaomi_philips_ceiling_light
          - light.yeelight_strip_7811dca220d2
          - switch.plug_158d0001deb419
          - switch.plug_158d0001de79e6
          - light.yeelight_strip_7811dc691c74
          - light.yeelight_color2_7c49eb1566bb
          - remote.jaskrowo_media
        type: entities
      - title: Kitchen
        entities:
          - sensor.temperature_158d0002320de3
          - sensor.humidity_158d0002320de3
          - binary_sensor.door_window_sensor_158d00023709f7
          - binary_sensor.door_window_sensor_158d00022f148a
          - light.yeelight_strip_7811dc68588d
          - light.gateway_light_34ce0088a579
          - vacuum.xiaomi_vacuum_cleaner
        type: entities
      - title: Tosia's bedroom
        entities:
          - sensor.temperature_158d0001b92092
          - sensor.humidity_158d0001b92092
          - binary_sensor.door_window_sensor_158d000232da46
          - light.yeelight_color2_7c49eb1582dd
          - switch.plug_158d0001ded32d
        type: entities
      - title: Guest room
        entities:
          - sensor.temperature_158d0002320e0c
          - sensor.humidity_158d0002320e0c
          - binary_sensor.door_window_sensor_158d0002436b09
          - light.xiaomi_philips_e14_crystal
          - light.xiaomi_philips_e14_crystal_2
        type: entities
      - title: Master bedroom
        entities:
          - sensor.temperature_158d0001b92145
          - sensor.humidity_158d0001b92145
          - sensor.temperature_158d0001b9208d
          - sensor.humidity_158d0001b9208d
          - binary_sensor.door_window_sensor_158d000232db84
          - light.xiaomi_philips_e14_frosted
          - light.yeelight_strip_7811dc66f063
          - light.gateway_light_34ce00fb56e8
        type: entities
      - title: Attic
        entities:
          - sensor.temperature_158d00023208a6
          - sensor.humidity_158d00023208a6
          - light.yeelight_color2_7c49eb1581f6
          - light.yeelight_color2_04cf8c7bf9ba
          - light.yeelight_color2_04cf8c7cc6ad
        type: entities
      - title: Air pollution
        entities:
          - sensor.waqi_kurdwanow_krakow_maopolska_poland
          - sensor.waqi_kurdwanow_krakow_maopolska_poland_pm_10
          - sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland
          - sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland_pm_10
          - sensor.waqi_skawina_maopolska_poland
          - sensor.waqi_skawina_maopolska_poland_pm_10
        type: entities
        show_header_toggle: false
      - title: Device battery
        entities:
          - sensor.battery_gosiak_mia2
          - sensor.battery_wiskra_mimix2
          - sensor.battery_wiskra_ipad
        theme: Backend-selected
        type: entities
        show_header_toggle: false
      - title: Network
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
          - sensor.asuswrt_download_speed
          - sensor.asuswrt_upload_speed
        type: entities
        show_header_toggle: false
      - type: weather-forecast
        entity: weather.krakow
      - title: Humidity
        entities:
          - sensor.humidity_158d0001b9208d
          - sensor.humidity_158d0001b92092
          - sensor.humidity_158d0001b92145
          - sensor.humidity_158d0001b1c3fb
          - sensor.humidity_158d00023208a6
          - sensor.humidity_158d0002320de3
          - sensor.humidity_158d0002320e0c
        hours_to_show: 24
        type: history-graph
        refresh_interval: 60
      - title: Air pollution
        entities:
          - sensor.waqi_kurdwanow_krakow_maopolska_poland
          - sensor.waqi_aleja_krasinskiego_krakow_maopolska_poland
          - sensor.waqi_skawina_maopolska_poland
        hours_to_show: 72
        type: history-graph
        refresh_interval: 3600
      - title: Windows open?
        entities:
          - binary_sensor.door_window_sensor_158d00023709f7
          - binary_sensor.door_window_sensor_158d0001ad5eb6
          - binary_sensor.door_window_sensor_158d00022f148a
          - binary_sensor.door_window_sensor_158d000232db84
          - binary_sensor.door_window_sensor_158d000232da46
          - binary_sensor.door_window_sensor_158d0002436b09
        hours_to_show: 24
        type: history-graph
        refresh_interval: 60
      - refresh_inteval: 60
        title: Temperature
        entities:
          - sensor.temperature_158d0001b9208d
          - sensor.temperature_158d0001b92092
          - sensor.temperature_158d0001b92145
          - sensor.temperature_158d0001b1c3fb
          - sensor.temperature_158d00023208a6
          - sensor.temperature_158d0002320de3
          - sensor.temperature_158d0002320e0c
        hours_to_show: 24
        type: history-graph
      - type: map
        aspect_ratio: 16:9
        default_zoom: 12
        entities:
          - device_tracker.gosiak_mia2
          - device_tracker.wiskra_mimix2
          - zone.home
  - title: Automations
    path: automations
    badges: []
    cards:
      - title: all automations
        entities:
          - automation.attic__empty_room
          - automation.attic__entry_area_motion
          - automation.attic__wardrobe_area_motion
          - automation.coming_home
          - automation.guest_room__bright_mode
          - automation.guest_room__motion
          - automation.guest_room__toggle_light
          - automation.hall__empty_room
          - automation.hall__motion
          - automation.kitchen__motion
          - automation.kitchen__empty
          - automation.leaving_home
          - automation.living_room__bright_enough
          - automation.living_room__empty_room
          - automation.living_room__stair_leds
          - automation.living_room_motion__01_normal
          - automation.living_room_motion__02_evening
          - automation.living_room_motion__03_tv_mode
          - automation.master_bedroom__empty
          - automation.master_bedroom__motion
          - automation.tosia_room__motion
          - automation.tosia_room__empty
          - automation.tosia_toggle_christmas_tree
          - automation.tosia_toggle_lamp
          - automation.turn_on_circadian_lighting_switches_on_startup
          - automation.windows_closed
          - automation.windows_open
        type: entities
      - title: People at home
        entities:
          - device_tracker.wiskra_1996c7e73ef9451bbe555b27c09d3c5d
          - device_tracker.wiskra_mimix2
          - device_tracker.gosiak_mia2
        type: entities
        show_header_toggle: false
      - title: Sunlight
        entities:
          - sun.sun
        type: entities
        show_header_toggle: false
      - title: Automatic brightness
        entities:
          - switch.circadian_lighting_attic_lights_auto
          - switch.circadian_lighting_guest_room_lights_auto
          - switch.circadian_lighting_hall_lights_auto
          - switch.circadian_lighting_living_room_auto_leds
          - switch.circadian_lighting_living_room_auto_ceiling
          - switch.circadian_lighting_master_bedroom_lights_auto
        type: entities
      - title: Switches
        entities:
          - binary_sensor.switch_158d00016dbe9e
          - binary_sensor.switch_158d00019ca9dc
          - binary_sensor.switch_158d00019d5813
          - binary_sensor.switch_158d0001b1827e
          - binary_sensor.switch_158d0001b182db
          - binary_sensor.switch_158d0001be5b10
          - binary_sensor.switch_158d0001d8eeb1
          - binary_sensor.switch_158d0001f9c3fe
        type: entities
      - type: entities
        title: Illumination
        show_header_toggle: false
        entities:
          - sensor.illumination_158d0001e43ac7
          - sensor.illumination_158d0001e43bc7
          - sensor.illumination_158d0001e4707c
          - sensor.illumination_158d0001e531e0
          - sensor.illumination_158d0001e532dc
          - sensor.illumination_158d0001e547ae
          - sensor.illumination_158d0001e55ff7
          - sensor.illumination_158d0002b70d79
          - sensor.illumination_158d0002b85113
          - sensor.illumination_158d0002b72030
          - sensor.illumination_158d0002b422b4
      - type: entities
        title: Motion detection
        show_header_toggle: false
        entities:
          - binary_sensor.motion_sensor_158d0001e43ac7
          - binary_sensor.motion_sensor_158d0001e43bc7
          - binary_sensor.motion_sensor_158d0001e4707c
          - binary_sensor.motion_sensor_158d0001e531e0
          - binary_sensor.motion_sensor_158d0001e532dc
          - binary_sensor.motion_sensor_158d0001e547ae
          - binary_sensor.motion_sensor_158d0001e55ff7
          - binary_sensor.motion_sensor_158d0002b70d79
          - binary_sensor.motion_sensor_158d0002b85113
          - binary_sensor.motion_sensor_158d0002b72030
          - binary_sensor.motion_sensor_158d0002b422b4
      - title: Lights temperature
        entities:
          - sensor.light_ct_philips_ceiling_light
          - sensor.light_ct_hall_light
        hours_to_show: 72
        type: history-graph
        refresh_time: 300
      - title: Lights brightness
        entities:
          - sensor.light_brightness_philips_ceiling_light
          - sensor.light_brightness_hall_light
        hours_to_show: 72
        type: history-graph
        refresh_time: 300
      - type: glance
        title: System load
        entities:
          - sensor.cpu_temperature
          - sensor.cpu_speed
          - sensor.load_5m
          - sensor.memory_use_percent
