title: Home
background: var(--background-image)
views:
  - title: Home
    icon: "mdi:home"
    path: default_view
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: media_player.spotify_wojciech_iskra
                state: "playing"
              - entity: sensor.spotify_source
                state_not: "Xiaomi Mi MIX 2"
            card:
              type: media-control
              entity: media_player.spotify_wojciech_iskra
          - title: Living room
            entities:
              - sensor.0x00158d0001b1c3fb_temperature
              - sensor.0x00158d0001b1c3fb_humidity
              - binary_sensor.0x00158d0001ad5eb6_contact
              - light.xiaomi_philips_ceiling_light
              - switch.shelly1_5556b7_relay_0
              - light.wall_leds
              # - switch.0x00158d0001de79e6_switch
              # - switch.fan
              - light.stairs_leds
              - light.downstairs_hall_lamp
              - switch.shelly1_554b82_relay_0
              - remote.jaskrowo_media
              - media_player.marantz_sr5008
              - input_boolean.someone_sleeping_in_the_living_room
            type: entities
      - type: vertical-stack
        cards:
          - title: Kitchen
            entities:
              - sensor.0x00158d0002320de3_temperature
              - sensor.0x00158d0002320de3_humidity
              - switch.shelly1_55df6e_relay_0
              - switch.shelly2_5a4ada_relay_0
              - switch.shelly2_5a4ada_relay_1
              - light.stove_leds
              - switch.0x00158d0003951e91_switch
              - binary_sensor.0x00158d00023709f7_contact
              - binary_sensor.0x00158d00022f148a_contact
              - vacuum.xiaomi_vacuum_cleaner
            type: entities
          - type: custom:xiaomi-vacuum-card
            entity: vacuum.xiaomi_vacuum_cleaner
            name: Vacuum
          # - type: glance
          #   entities:
          #     - icon: "mdi:water"
          #       type: entity-button
          #       entity: script.vacuum_start_mopping
          #       tap_action:
          #         action: call-service
          #         service: script.turn_on
          #         service_data:
          #           entity_id: script.vacuum_start_mopping
          #     - icon: "mdi:robot-vacuum"
          #       type: entity-button
          #       entity: script.vacuum_start_cleaning
          #       tap_action:
          #         action: call-service
          #         service: script.turn_on
          #         service_data:
          #           entity_id: script.vacuum_start_cleaning
          #     - icon: "mdi:pause"
          #       type: entity-button
          #       entity: script.vacuum_pause
          #       tap_action:
          #         action: call-service
          #         service: script.turn_on
          #         service_data:
          #           entity_id: script.vacuum_pause
          #     - icon: "mdi:home-circle"
          #       type: entity-button
          #       entity: script.vacuum_go_home
          #       tap_action:
          #         action: call-service
          #         service: script.turn_on
          #         service_data:
          #           entity_id: script.vacuum_go_home
      - title: Master bedroom
        entities:
          - sensor.0x00158d0001b92145_temperature
          - sensor.0x00158d0001b92145_humidity
          - sensor.0x00158d0001b9208d_temperature
          - sensor.0x00158d0001b9208d_humidity
          - binary_sensor.0x00158d000232db84_contact
          - light.master_bedroom_bed_lamp
          - light.bed_leds
          - switch.shelly1_2c03c5_relay_0
          - switch.shelly1_55e273_relay_0
          - light.gateway_light_34ce00fb56e8
        type: entities
      - title: Tosia's bedroom
        entities:
          - sensor.0x00158d00033b4d2c_temperature
          - sensor.0x00158d00033b4d2c_humidity
          - binary_sensor.0x00158d000232da46_contact
          - light.0xec1bbdfffeb7fbbc_light
          - light.0x00158d0002b88c1c_light
          - light.tosia_lamp
          # - switch.0x00158d0003951ef9_switch
        type: entities
      - title: Guest room
        entities:
          - sensor.0x00158d0002320e0c_temperature
          - sensor.0x00158d0002320e0c_humidity
          - binary_sensor.0x00158d0002436b09_contact
          - light.xiaomi_philips_e14_crystal
          - light.xiaomi_philips_e14_crystal_2
          - fan.xiaomi_smart_fan
          - switch.0x00158d00039e5eb1_switch
        type: entities
      # - entity: fan.xiaomi_smart_fan
      #   name: Big fan
      #   type: "custom:fan-xiaomi"
      # - type: conditional
      #   conditions:
      #     - entity: fan.xiaomi_smart_fan
      #       state: "on"
      #   card:
      #     - entity: fan.xiaomi_smart_fan
      #       name: Big fan
      #       type: "custom:fan-xiaomi"
      - type: conditional
        conditions:
          - entity: sensor.zwift_online_1380479
            state: "True"
        card:
          type: entities
          title: Wojtek is training
          icon: "mdi:bike"
          entities:
            - sensor.zwift_level_1380479
            - sensor.zwift_distance_1380479
            - sensor.zwift_power_1380479
            - sensor.zwift_heart_rate_1380479
            - sensor.zwift_cadence_1380479
      - title: Attic
        entities:
          - sensor.0x00158d00023208a6_temperature
          - sensor.0x00158d00023208a6_humidity
          - light.0x00158d0003fa55ab_light
          - light.attic_right_lamp_light
          - light.0x00158d000410f2db_light
        type: entities
      - title: Bathrooms
        entities:
          - light.downstairs_bathroom_ceiling_lamp
          - light.downstairs_bathroom_side_lamp
          - switch.shelly1_5545a9_relay_0
        type: entities
      - title: Upstairs hall
        entities:
          - light.upstairs_hall_left_lamp
          - light.upstairs_hall_right_lamp
          - light.wardrobe_lamp
        type: entities
      # - type: media-control
      #   entity: media_player.marantz_sr5008
      - title: Air pollution
        entities:
          - sensor.xiaomi_air_quality_monitor
          - sensor.airly_air_quality_index
          - sensor.airly_advice
        type: entities
        show_header_toggle: false
      - title: Device battery
        entities:
          - sensor.gosiak_mia2_2_battery_level
          - sensor.wojtek_mimix2_battery_level
          - sensor.wojtek_s_ipad_battery_level
        theme: Backend-selected
        type: entities
        show_header_toggle: false
      - title: Windows open?
        entities:
          - binary_sensor.0x00158d00023709f7_contact
          - binary_sensor.0x00158d0001ad5eb6_contact
          - binary_sensor.0x00158d00022f148a_contact
          - binary_sensor.0x00158d000232db84_contact
          - binary_sensor.0x00158d000232da46_contact
          - binary_sensor.0x00158d0002436b09_contact
        hours_to_show: 24
        type: history-graph
        refresh_interval: 60
      - type: weather-forecast
        entity: weather.dark_sky
      - type: vertical-stack
        title: COVID-19 status
        cards:
          - type: history-graph
            title: "Worldwide"
            hours_to_show: 168
            refresh_interval: 3600
            entities:
              - sensor.worldwide_coronavirus_confirmed
              - sensor.worldwide_coronavirus_recovered
              - sensor.worldwide_coronavirus_deaths
          - type: history-graph
            title: "Poland"
            hours_to_show: 168
            refresh_interval: 3600
            entities:
              - sensor.poland_coronavirus_confirmed
              - sensor.poland_coronavirus_recovered
              - sensor.poland_coronavirus_deaths
