title: Home
resources:
  - url: /local/surveillance-card.js?v=1
    type: module
views:
  - title: Home
    path: default_view
    badges: []
    cards:
      - title: Living room
        entities:
          - sensor.temperature_158d0001b1c3fb
          - sensor.humidity_158d0001b1c3fb
          - binary_sensor.door_window_sensor_158d0001ad5eb6
          - light.xiaomi_philips_ceiling_light
          - switch.living_room_wall
          - light.wall_leds
          - light.stairs_leds
          - light.downstairs_hall_lamp
          - switch.living_room_stair
          - fan.xiaomi_smart_fan
          - remote.jaskrowo_media
          - media_player.marantz_sr5008
        type: entities
      - title: Kitchen
        entities:
          - sensor.temperature_158d0002320de3
          - sensor.humidity_158d0002320de3
          - switch.kitchen_lights
          - switch.dining_room_ceiling
          - switch.dining_room_wall
          - light.stove_leds
          - switch.plug_158d0001ded32d
          - switch.fan
          - binary_sensor.door_window_sensor_158d00023709f7
          - binary_sensor.door_window_sensor_158d00022f148a
          - vacuum.xiaomi_vacuum_cleaner
        type: entities
      - title: Master bedroom
        entities:
          - sensor.temperature_158d0001b92145
          - sensor.humidity_158d0001b92145
          - sensor.temperature_158d0001b9208d
          - sensor.humidity_158d0001b9208d
          - binary_sensor.door_window_sensor_158d000232db84
          - light.master_bedroom_bed_lamp
          - light.bed_leds
          - switch.master_bedroom_wall
          - switch.master_bedroom_stair
          - light.gateway_light_34ce00fb56e8
        type: entities
      - title: Tosia's bedroom
        entities:
          - sensor.temperature_158d0001b92092
          - sensor.humidity_158d0001b92092
          - binary_sensor.door_window_sensor_158d000232da46
          - light.tosia_left_wall_lamp
          - light.right_wall_lamp
          - light.tosia_lamp
        type: entities
      - title: Guest room
        entities:
          - sensor.temperature_158d0002320e0c
          - sensor.humidity_158d0002320e0c
          - binary_sensor.door_window_sensor_158d0002436b09
          - light.xiaomi_philips_e14_crystal
          - light.xiaomi_philips_e14_crystal_2
          - switch.xiaomi_miio_switch
        type: entities
      - title: Attic
        entities:
          - sensor.temperature_158d00023208a6
          - sensor.humidity_158d00023208a6
          - light.attic_left_light
          - light.attic_right_light
          - light.attic_wardrobe_area_light
        type: entities
      - title: Bathrooms
        entities:
          - light.downstairs_bathroom_lamp
          - switch.downstairs_bathroom_side
          - switch.upstairs_bathroom_ceiling
        type: entities
      - title: Upstairs hall
        entities:
          - light.upstairs_hall_left_lamp
          - light.upstairs_hall_right_lamp
          - light.wardrobe_lamp
        type: entities
      # - type: media-control
      #   entity: media_player.marantz_sr5008
      # - type: picture-glance
      #   title: Living room
      #   entities:
      #     - sensor.temperature_158d0001b1c3fb
      #     - sensor.humidity_158d0001b1c3fb
      #     - image_processing.face_counter
      #     - light.xiaomi_philips_ceiling_light
      #     - light.wall_leds
      #   camera_image: camera.ffmpeg
      - title: Air pollution
        entities:
          - sensor.xiaomi_air_quality_monitor
          - sensor.airly_caqi
          - sensor.airly_description
        type: entities
        show_header_toggle: false
      - title: Device battery
        entities:
          - sensor.battery_gosiak_mia2
          - sensor.battery_wiskra_mimix2
          - sensor.battery_wiskra_ipad
        theme: Backend-selected
        type: entities
        show_header_toggle: false
      - title: Network
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
          - sensor.asuswrt_download_speed
          - sensor.asuswrt_upload_speed
        type: entities
        show_header_toggle: false
      - type: weather-forecast
        entity: weather.home
      - title: Humidity
        entities:
          - sensor.humidity_158d0001b9208d
          - sensor.humidity_158d0001b92092
          - sensor.humidity_158d0001b92145
          - sensor.humidity_158d0001b1c3fb
          - sensor.humidity_158d00023208a6
          - sensor.humidity_158d0002320de3
          - sensor.humidity_158d0002320e0c
        hours_to_show: 24
        type: history-graph
        refresh_interval: 60
      # - title: Air pollution
      #   entities:
      #     - sensor.airly_caqi
      #     - sensor.airly_pm2_5
      #     - sensor.airly_pm10
      #   hours_to_show: 72
      #   type: history-graph
      #   refresh_interval: 900
      - title: Windows open?
        entities:
          - binary_sensor.door_window_sensor_158d00023709f7
          - binary_sensor.door_window_sensor_158d0001ad5eb6
          - binary_sensor.door_window_sensor_158d00022f148a
          - binary_sensor.door_window_sensor_158d000232db84
          - binary_sensor.door_window_sensor_158d000232da46
          - binary_sensor.door_window_sensor_158d0002436b09
        hours_to_show: 24
        type: history-graph
        refresh_interval: 60
      - refresh_inteval: 60
        title: Temperature
        entities:
          - sensor.temperature_158d0001b9208d
          - sensor.temperature_158d0001b92092
          - sensor.temperature_158d0001b92145
          - sensor.temperature_158d0001b1c3fb
          - sensor.temperature_158d00023208a6
          - sensor.temperature_158d0002320de3
          - sensor.temperature_158d0002320e0c
          - sensor.airly_temperature
        hours_to_show: 24
        type: history-graph
      - type: map
        aspect_ratio: 16:9
        default_zoom: 12
        entities:
          - device_tracker.gosiak_mia2_2
          - device_tracker.wiskra_mimix2_2
          - zone.home
      - type: glance
        title: Vacuum
        entities:
          - icon: 'mdi:water'
            type: entity-button
            entity: script.vacuum_start_mopping
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.vacuum_start_mopping
          - icon: 'mdi:robot-vacuum'
            type: entity-button
            entity: script.vacuum_start_cleaning
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.vacuum_start_cleaning
          - icon: 'mdi:pause'
            type: entity-button
            entity: script.vacuum_pause
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.vacuum_pause
          - icon: 'mdi:home-circle'
            type: entity-button
            entity: script.vacuum_go_home
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.vacuum_go_home
  - title: Automations
    path: automations
    badges: []
    cards:
      - title: all automations
        entities:
          - automation.attic_empty_room
          - automation.attic_entry_area_motion
          - automation.attic_wardrobe_area_motion
          - automation.dining_area_empty
          - automation.downstairs_bathroom_motion
          - automation.downstairs_bathroom_empty
          - automation.guest_room_bright_mode
          - automation.guest_room_motion
          - automation.hall_empty_room
          - automation.hall_motion
          - automation.kitchen_motion_daytime
          - automation.kitchen_motion_at_night
          - automation.kitchen_empty
          - automation.kitchen_bright_enough
          - automation.leaving_home
          - automation.living_room_bright_enough
          - automation.living_room_empty_room
          - automation.living_room_stair_leds
          - automation.living_room_stairs_motion
          - automation.living_room_stairs_empty
          - automation.living_room_motion_01_normal
          - automation.living_room_motion_02_evening
          - automation.living_room_motion_03_tv_mode
          - automation.living_room_turn_on_fan_daytime
          - automation.living_room_turn_on_fan_evening
          - automation.master_bedroom_empty
          - automation.master_bedroom_motion
          - automation.smog_air_is_clean
          - automation.smog_close_the_windows
          - automation.tosia_room_motion
          - automation.tosia_room_empty
          - automation.tosia_toggle_christmas_tree
          - automation.tosia_toggle_lamp
          - automation.turn_on_circadian_lighting_switches_on_startup
          - automation.upstairs_bathroom_motion
          - automation.upstairs_bathroom_empty
          - automation.upstairs_hall_motion
          - automation.upstairs_hall_empty
          - automation.wardrobe_motion
          - automation.wardrobe_empty
        type: entities
      - title: People at home
        entities:
          - device_tracker.wojtek_1996c7e7_3ef9_451b_be55_5b27c09d3c5d
          - device_tracker.wiskra_mimix2_2
          - device_tracker.gosiak_mia2_2
        type: entities
        show_header_toggle: false
      - title: Sunlight
        entities:
          - sun.sun
        type: entities
        show_header_toggle: false
      - title: Automatic brightness
        entities:
          - switch.circadian_lighting_attic_lights_auto
          - switch.circadian_lighting_guest_room_lights_auto
          - switch.circadian_lighting_hall_lights_auto
          - switch.circadian_lighting_living_room_auto_leds
          - switch.circadian_lighting_living_room_auto_ceiling
          - switch.circadian_lighting_master_bedroom_lights_auto
          - switch.circadian_lighting_tosia_room_lights_auto
        type: entities
      - title: Switches
        entities:
          - binary_sensor.switch_158d00016dbe9e
          - binary_sensor.switch_158d00019ca9dc
          - binary_sensor.switch_158d00019d5813
          - binary_sensor.switch_158d0001b1827e
          - binary_sensor.switch_158d0001b182db
          - binary_sensor.switch_158d0001be5b10
          - binary_sensor.switch_158d0001d8eeb1
          - binary_sensor.switch_158d0001f9c3fe
        type: entities
      - type: entities
        title: Illumination
        show_header_toggle: false
        entities:
          - sensor.illumination_34ce0088a579
          - sensor.illumination_158d0001e43ac7
          - sensor.illumination_158d0001e4707c
          - sensor.illumination_158d0001e531e0
          - sensor.illumination_158d0002b422b4
          - sensor.illumination_158d0001e43bc7
          - sensor.illumination_34ce00fb56e8
          - sensor.illumination_158d0001e532dc
          - sensor.illumination_158d0002b85113
          - sensor.illumination_158d0002b70d79
          - sensor.illumination_158d0002b72030
          - sensor.illumination_158d0001e547ae
          - sensor.illumination_158d0001e55ff7
          - sensor.illumination_158d0002ec7efa
          - sensor.illumination_158d000257a1be
          - sensor.illumination_158d000257a1db
      - type: entities
        title: Motion detection
        show_header_toggle: false
        entities:
          - binary_sensor.motion_sensor_158d0001e43ac7
          - binary_sensor.motion_sensor_158d0001e43bc7
          - binary_sensor.motion_sensor_158d0001e4707c
          - binary_sensor.motion_sensor_158d0001e531e0
          - binary_sensor.motion_sensor_158d0001e532dc
          - binary_sensor.motion_sensor_158d0001e547ae
          - binary_sensor.motion_sensor_158d0001e55ff7
          - binary_sensor.motion_sensor_158d0002b70d79
          - binary_sensor.motion_sensor_158d0002b85113
          - binary_sensor.motion_sensor_158d0002b72030
          - binary_sensor.motion_sensor_158d0002b422b4
          - binary_sensor.motion_sensor_158d000257a1db
          - binary_sensor.motion_sensor_158d0002ec7efa
          - binary_sensor.motion_sensor_158d0001655da1
      - title: Lights temperature
        entities:
          - sensor.light_ct_philips_ceiling_light
          - sensor.light_ct_hall_light
        hours_to_show: 72
        type: history-graph
        refresh_time: 300
      - title: Lights brightness
        entities:
          - sensor.light_brightness_philips_ceiling_light
          - sensor.light_brightness_hall_light
        hours_to_show: 72
        type: history-graph
        refresh_time: 300
      - type: glance
        title: System load
        entities:
          - sensor.cpu_temperature
          - sensor.cpu_speed
          - sensor.load_5m
          - sensor.memory_use_percent
  # - title: Surveillance
  #   icon: mdi:cctv
  #   panel: true
  #   cards:
  #     - type: custom:surveillance-card
  #       thumb_interval: "0.5"
  #       update_interval: "0.5"
  #       cameras:
  #         - entity: camera.ffmpeg
  #           motion_entity: binary_sensor.motion_sensor_158d0001e547ae
