title: Home
background: var(--background-image)
views:
  - title: Home
    icon: "mdi:home"
    path: default_view
    badges: []
    cards:
      - type: conditional
        conditions:
          - entity: binary_sensor.ping_wp_pl
            state: "off"
        card:
          type: markdown
          content: >
            # We're offline!

            ### Internet is down at the moment! 😱
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - entity: media_player.spotify_wojciech_iskra
                state: "playing"
            card:
              type: media-control
              entity: media_player.spotify_wojciech_iskra
          - type: conditional
            conditions:
              - entity: media_player.kodi_259e2e8eb818649f98da60614c9822c3
                state: "playing"
            card:
              type: media-control
              entity: media_player.kodi_259e2e8eb818649f98da60614c9822c3
          - title: Living room
            entities:
              - sensor.0x00158d0001b1c3fb_temperature
              - sensor.0x00158d0001b1c3fb_humidity
              - binary_sensor.0x00158d0001ad5eb6_contact
              - light.xiaomi_philips_ceiling_light
              - group.living_room_ceiling_lights
              - light.shelly_rgbw2_6ea3da_light_0
              # - switch.0x00158d0001de79e6_switch
              # - switch.shelly_plug_s_51d5ae_relay_0
              - light.stairs_leds
              - group.downstairs_hall_lights
              - group.living_room_stairs_lights
              - fan.fan_2
              - remote.jaskrowo_media
              - media_player.marantz_sr5008
              - input_boolean.someone_sleeping_in_the_living_room
            type: entities
          # - entity: fan.fan_2
          #   name: Big fan
          #   type: "custom:fan-xiaomi"
          # - type: conditional
          #   conditions:
          #     - entity: fan.fan_2
          #       state: "on"
          #   card:
          #     - entity: fan.fan_2
          #       name: Big fan
          #       type: "custom:fan-xiaomi"
      - type: vertical-stack
        cards:
          - title: Kitchen
            entities:
              - sensor.0x00158d0002320de3_temperature
              - sensor.0x00158d0002320de3_humidity
              - group.kitchen_ceiling_lights
              - light.0x00158d0004210bb5_light
              - light.dining_area_ceiling_lamp
              - light.stove_leds
              - switch.0x00158d0003951e91_switch
              - binary_sensor.0x00158d00023709f7_contact
              - binary_sensor.0x00158d00022f148a_contact
              - vacuum.xiaomi_vacuum_cleaner
            type: entities
          - type: custom:xiaomi-vacuum-card
            entity: vacuum.xiaomi_vacuum_cleaner
            name: Vacuum
          # - type: glance
          #   entities:
          #     - icon: "mdi:water"
          #       type: entity-button
          #       entity: script.vacuum_start_mopping
          #       tap_action:
          #         action: call-service
          #         service: script.turn_on
          #         service_data:
          #           entity_id: script.vacuum_start_mopping
          #     - icon: "mdi:robot-vacuum"
          #       type: entity-button
          #       entity: script.vacuum_start_cleaning
          #       tap_action:
          #         action: call-service
          #         service: script.turn_on
          #         service_data:
          #           entity_id: script.vacuum_start_cleaning
          #     - icon: "mdi:pause"
          #       type: entity-button
          #       entity: script.vacuum_pause
          #       tap_action:
          #         action: call-service
          #         service: script.turn_on
          #         service_data:
          #           entity_id: script.vacuum_pause
          #     - icon: "mdi:home-circle"
          #       type: entity-button
          #       entity: script.vacuum_go_home
          #       tap_action:
          #         action: call-service
          #         service: script.turn_on
          #         service_data:
          #           entity_id: script.vacuum_go_home
      - title: Master bedroom
        entities:
          - sensor.0x00158d0001b92145_temperature
          - sensor.0x00158d0001b92145_humidity
          - sensor.0x00158d0001b9208d_temperature
          - sensor.0x00158d0001b9208d_humidity
          - binary_sensor.0x00158d000232db84_contact
          - light.master_bedroom_bed_lamp
          - light.bed_leds
          - light.shelly_rgbw2_6d8073_light_0
          - switch.shelly_1_2c03c5_relay_0
          - group.master_bedroom_ceiling_lights
          - climate.room_air_conditioner
          - sensor.room_air_conditioner_power_consumption_power
        type: entities
      - title: Tosia's bedroom
        entities:
          - sensor.0x00158d00033b4d2c_temperature
          - sensor.0x00158d00033b4d2c_humidity
          - binary_sensor.0x00158d000232da46_contact
          - light.0xec1bbdfffeb7fbbc_light
          - light.0x00158d0002b88c1c_light
          - light.tosia_lamp
          # - switch.0x00158d0003951ef9_switch
          # - switch.0x00158d0001ded32d_switch
        type: entities
      - title: Guest room
        entities:
          - sensor.0x00158d0002320e0c_temperature
          - sensor.0x00158d0002320e0c_humidity
          - binary_sensor.0x00158d0002436b09_contact
          - light.xiaomi_philips_e14_crystal
          - light.xiaomi_philips_e14_crystal_2
          - switch.0x00158d00039e5eb1_switch
        type: entities
      - type: conditional
        conditions:
          - entity: sensor.zwift_online_1380479
            state: "True"
        card:
          type: entities
          title: Wojtek is training
          icon: "mdi:bike"
          entities:
            - sensor.zwift_level_1380479
            - sensor.zwift_distance_1380479
            - sensor.zwift_power_1380479
            - sensor.zwift_heart_rate_1380479
            - sensor.zwift_cadence_1380479
      - title: Attic
        entities:
          - sensor.0x00158d00023208a6_temperature
          - sensor.0x00158d00023208a6_humidity
          - light.0x00158d0003fa55ab_light
          - light.attic_right_lamp_light
          - light.shelly_rgbw2_f43a41_light_0
          - light.0x00158d000410f2db_light
          - light.attic_closet_lamp
          - fan.xiaomi_smart_fan
        type: entities
      - title: Bathrooms
        entities:
          - light.downstairs_bathroom_ceiling_lamp
          - group.downstairs_bathroom_mirror
          - switch.shelly_1_5545a9_relay_0
          - sensor.shelly_plug_s_51d92a_power_0_2
        type: entities
      - title: Upstairs hall
        entities:
          - group.upstairs_hall_lights
          - light.wardrobe_lamp
          - input_boolean.someone_s_ironining
        type: entities
      # - type: media-control
      #   entity: media_player.marantz_sr5008
      - title: Air pollution
        entities:
          - sensor.xiaomi_air_quality_monitor
          - sensor.airly_air_quality_index
          - sensor.airly_advice
        type: entities
        show_header_toggle: false
      - title: Device battery
        entities:
          - sensor.gosiak_pixel_3_battery_level
          - sensor.google_pixel_slate_battery_level
          - sensor.tosia_mi_a2_lite_poziom_baterii
          - sensor.in2013_battery_level
          - sensor.wojtek_s_ipad_battery_level
        theme: Backend-selected
        type: entities
        show_header_toggle: false
      - title: Windows open?
        entities:
          - binary_sensor.0x00158d00023709f7_contact
          - binary_sensor.0x00158d0001ad5eb6_contact
          - binary_sensor.0x00158d00022f148a_contact
          - binary_sensor.0x00158d000232db84_contact
          - binary_sensor.0x00158d000232da46_contact
          - binary_sensor.0x00158d0002436b09_contact
        hours_to_show: 24
        type: history-graph
        refresh_interval: 60
      - type: weather-forecast
        entity: weather.home
